# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 12, 47, 55, 728000, tzinfo=utc)),
        ),
    ]
